install:
  - cinst pester

version: 1.0.{build}
build_script:
- ps: New-ModuleManifest -ModuleVersion $ENV:APPVEYOR_BUILD_VERSION -Path .\LoremIpsum.psd1 -Author 'Adam Driscoll' -Company 'Concurrency, Inc' -Description 'Generates LoremIpsum text.' -RootModule '.\LoremIpsum.psm1' -FunctionsToExport 'New-LoremIpsum' 

test_script:
  - ps: $res = Invoke-Pester -Path ".\" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  